### ISSUE TITLE
http://git.io/vmW3z - wrong url?

### ISSUE THREAD

**Issue by Ozzyboshi** [weaveworks/discovery#6]
In the installation paragraph you suggest to download the discovery script with

```
curl -O http://git.io/vmW3z
```

I assumed that this url pointed to a script file, actually it's pointing to the github web page.
Maybe the documentation is wrong?

Looking forward for the next discovery related post on the weave works website blog.

**Comment by inercia** [comment]
Thanks for pointing this out @Ozzyboshi. I'll fix it.

**Comment by inercia** [comment]
Fixed. Removed the short URL until we find a better solution.
